version: '3'

vars:
  IMAGE_NAME: ghcr.io/alextreichler/personal-website
  BINARY_NAME: personal-website
  # Use git describe to get a version string (e.g., v1.0.0-3-g123abc) or fallback to short hash
  VERSION: 
    sh: git describe --tags --always --dirty 2>/dev/null || git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the Go binary locally
    cmds:
      - echo "Building {{.BINARY_NAME}}..."
      - mkdir -p bin
      - CGO_ENABLED=0 go build -o bin/{{.BINARY_NAME}} ./cmd/server

  run:
    desc: Run the application locally
    cmds:
      - go run ./cmd/server

  clean:
    desc: Remove built binaries
    cmds:
      - rm -rf bin/

  image:
    desc: Build the container image with version and latest tags
    cmds:
      - echo "Building Docker image {{.IMAGE_NAME}}:{{.VERSION}}"
      - docker build -t {{.IMAGE_NAME}}:{{.VERSION}} -t {{.IMAGE_NAME}}:latest .

  push:
    desc: Push the container image to registry
    deps: [image]
    cmds:
      - echo "Pushing {{.IMAGE_NAME}}:{{.VERSION}}"
      - docker push {{.IMAGE_NAME}}:{{.VERSION}}
      - echo "Pushing {{.IMAGE_NAME}}:latest"
      - docker push {{.IMAGE_NAME}}:latest

  release:
    desc: Full release flow: Test -> Build Image -> Push
    cmds:
      # Optional: Add a test step here if you want to enforce tests before release
      # - task: test
      - task: push
      - echo "Release {{.VERSION}} pushed successfully!"